version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - restore_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          working_directory: ./var/www/app
      - run:
          command: composer install -n --prefer-dist
          working_directory: ./var/www/app
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          working_directory: ./var/www/app
          paths:
            - vendor
      - run:
          command: npm ci
          working_directory: ./var/www/app
      - run:
          command: npm run dev
          working_directory: ./var/www/app
      - run:
          name: php test
          command: vendor/bin/phpunit
          working_directory: ./var/www/app
