version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - restore_cache:
          key: composer-v1-{{ checksum "./var/www/app/composer.lock" }}
      - run:
          command: composer install -n --prefer-dist
          working_directory: ./var/www/app
      - save_cache:
          key: composer-v1-{{ checksum "./var/www/app/composer.lock" }}
          paths:
            - vendor
      - restore_cache:
          key: composer-v1-{{ checksum "./var/www/app/package-lock.json" }}
      - run:
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
          working_directory: ./var/www/app
      - save_cache:
          key: npm-v1-{{ checksum "./var/www/app/package-lock.json" }}
          paths:
            - node_modules
      - run:
          command: npm run dev
          working_directory: ./var/www/app
      - run:
          name: php test
          command: vendor/bin/phpunit
          working_directory: ./var/www/app
